# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.13

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/csuser/CPSC223/hw3-MAviles-Baquero

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/csuser/CPSC223/hw3-MAviles-Baquero

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/csuser/CPSC223/hw3-MAviles-Baquero/CMakeFiles /home/csuser/CPSC223/hw3-MAviles-Baquero/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/csuser/CPSC223/hw3-MAviles-Baquero/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named hw3test

# Build rule for target.
hw3test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hw3test
.PHONY : hw3test

# fast build rule for target.
hw3test/fast:
	$(MAKE) -f CMakeFiles/hw3test.dir/build.make CMakeFiles/hw3test.dir/build
.PHONY : hw3test/fast

#=============================================================================
# Target rules for targets named hw3perf

# Build rule for target.
hw3perf: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hw3perf
.PHONY : hw3perf

# fast build rule for target.
hw3perf/fast:
	$(MAKE) -f CMakeFiles/hw3perf.dir/build.make CMakeFiles/hw3perf.dir/build
.PHONY : hw3perf/fast

hw3_perf.o: hw3_perf.cpp.o

.PHONY : hw3_perf.o

# target to build an object file
hw3_perf.cpp.o:
	$(MAKE) -f CMakeFiles/hw3perf.dir/build.make CMakeFiles/hw3perf.dir/hw3_perf.cpp.o
.PHONY : hw3_perf.cpp.o

hw3_perf.i: hw3_perf.cpp.i

.PHONY : hw3_perf.i

# target to preprocess a source file
hw3_perf.cpp.i:
	$(MAKE) -f CMakeFiles/hw3perf.dir/build.make CMakeFiles/hw3perf.dir/hw3_perf.cpp.i
.PHONY : hw3_perf.cpp.i

hw3_perf.s: hw3_perf.cpp.s

.PHONY : hw3_perf.s

# target to generate assembly for a file
hw3_perf.cpp.s:
	$(MAKE) -f CMakeFiles/hw3perf.dir/build.make CMakeFiles/hw3perf.dir/hw3_perf.cpp.s
.PHONY : hw3_perf.cpp.s

hw3_test.o: hw3_test.cpp.o

.PHONY : hw3_test.o

# target to build an object file
hw3_test.cpp.o:
	$(MAKE) -f CMakeFiles/hw3test.dir/build.make CMakeFiles/hw3test.dir/hw3_test.cpp.o
.PHONY : hw3_test.cpp.o

hw3_test.i: hw3_test.cpp.i

.PHONY : hw3_test.i

# target to preprocess a source file
hw3_test.cpp.i:
	$(MAKE) -f CMakeFiles/hw3test.dir/build.make CMakeFiles/hw3test.dir/hw3_test.cpp.i
.PHONY : hw3_test.cpp.i

hw3_test.s: hw3_test.cpp.s

.PHONY : hw3_test.s

# target to generate assembly for a file
hw3_test.cpp.s:
	$(MAKE) -f CMakeFiles/hw3test.dir/build.make CMakeFiles/hw3test.dir/hw3_test.cpp.s
.PHONY : hw3_test.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... hw3test"
	@echo "... hw3perf"
	@echo "... hw3_perf.o"
	@echo "... hw3_perf.i"
	@echo "... hw3_perf.s"
	@echo "... hw3_test.o"
	@echo "... hw3_test.i"
	@echo "... hw3_test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

